### ISSUE TITLE
Linux and MMU

### ISSUE THREAD

**Issue by letarg0** [zephray/VerilogBoy#18]
In my opinion ARM (or whatewer else) procesor must have Memory unit for normal system like Linux. Linux can work on AT286 x86 but is not stable similar other project https://hackaday.com/2015/05/21/unix-on-your-breadboard/ etc.
MMU is very safety.

Second trouble is network. Today Lora, Wifi is very important. Think about this.

**Comment by zephray** [comment]
Wait... But I don’t have Linux anywhere in the project, and that small ARM micro controller is subject to be removed. Networking can be a great add on, but only if it is possible to do so. Currently the size is the main limitation.

**Comment by letarg0** [comment]
Every system need **MMU**. 
Linux is for network, and meybe a second devices/core etc. MMU is for any system. Not only Linux.

MMU is important for any processor ;-) this is protect mode for separate programs. Look at psp, ps3 or other. One core is for system (prev. 2 cores) and other for game.

I like https://www.clockworkpi.com/ because i can easy write program. but...
meybe Your processor will be only coprocesor? Look at dingoo (small homebrew game console) or pandora. Simple mruby or embeded python can using MMU.

**Comment by zephray** [comment]
I still do not understand your argument. There is absolutely no operating system running on it. The processor only handles power management and you can **not** run any user program on the processor.

I think you misunderstand the project.

For the VerilogBoy Handheld, this is an FPGA based handheld console, the main component here is the FPGA rather than a processor. The microcontroller is added merely for handling hardware specific configurations like codec or power management, also firmware upgrade for the FPGA. It is not designed to be user programmable, and is likely to be removed in the future in favor of doing everything inside the FPGA.

For the VerilogBoy Core, this is a re-creation of a GameBoy(R) compatible machine. The GameBoy does NOT have an MMU, so I don't see the point of adding an MMU to it since absolutely no software or game designed for GameBoy would utilize the MMU.

I understand the function of the MMU, and I know why I do not need an MMU. The Game runs in a separate processor inside the FPGA. It is a completely different processor with completely isolated memory space. There is no way they can interfere with each other by writing the memory.

If your argument is about, you want to develop software (game) for the console, and you really want an MMU to protect your code from doing anything stupid, plus you are not interested in the idea of GameBoy(R) compatible: yes sure. You can throw a processor with MMU like VexRiscv or something into the FPGA and use it as a RISC-V game console. But that's out of the scope of this project.

**Comment by zephray** [comment]
Thanks for opening up the issue. If I have answered your question, please close the issue. MMU is a necessity for multi-threaded operating system or any other case where memory sharing is required. But for this project, adding an MMU to an 80s 8-bit GameBoy architecture doesn't make much sense here. I will consider adding an MMU if other 32-bit soft processor is supported in the future.
